### PR TITLE
Best practices applied

### PR DESCRIPTION
**Pull request by ashish-sjc**

### CODE REVIEW

**Comment by karanarora** [comment]
@ashish-sjc please fix line 12.

**Comment by ashish-sjc** [comment]
@karanarora whats up with that ?

**Comment by karanarora** [comment]
should be ?
`valid ? response.collect!{|r| r['name']} : response`

**Comment by karanarora** [comment]
@ashish-sjc ^^

**Comment by ashish-sjc** [comment]
done!

**Comment by karanarora** [comment]
@ashish-sjc  thanks for contributing :)

**Pull request merged**
